### ISSUE TITLE
STLReader.read returns null

### ISSUE THREAD

**Issue by ksons** [tatx/stl-reader#1]
If arrayBuffer2String is used, the callback is executed asynchronously and therefore the read method returns undefined but the result of the StlAsciiReader is never returned:

https://github.com/tatx/stl-reader/blob/master/stl-reader.js#L81

**Comment by ksons** [comment]
DataStream.js has a method to convert to string, so why not use:

 reader = new StlAsciiReader();
 ds.seek(0);
 return reader.read(ds.readString());

**Comment by tatx** [comment]
Thanks @ksons for catching this and suggesting the right fix! I have committed changes and published a new version. Thanks!

**Comment by ksons** [comment]
Thanks for fixing and the fast response!
